### ISSUE TITLE
Hooking Settings files not found when upgrading to new version

### ISSUE THREAD

**Issue by xnl-h4ck3r** [kevin-mizu/domloggerpp#11]
Hi Kevin
I was just wondering exactly where the Hooking Setting files were created? I couldn't work out where it was.
I created one in version 1.0.4 and need to move it to the new version, but it doesn't automatically find it. I guess it could be better if they are automatically stored in a shared location that any version can access.
Thanks

**Comment by kevin-mizu** [comment]
Hey 👋

Are you saying that you lost all your configuration JSON after upgrading to the new version? That's odd!

Currently, configurations are stored using the storage API ([documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage)). The associated data should be available from disk as it uses persistent storage. I'll look into the specific location by the end of the week

Also, you shouldn't lose your configs unless you've uninstalled the extension. Maybe you deleted it to reinstall the latest version from the store? If so, you don't need to do that. By default, the browser checks for new extension updates in the store frequently and updates them when found :D

Cheers,
Kévin

**Comment by xnl-h4ck3r** [comment]
Hi @kevin-mizu. I was installing it by downloading the latest zip in releases on github, so it installed as a new version! I hadn't realised it was on the Chrome Web Store! I've just installed that version instead so will be updated automatically instead. I saved a copy of my config anyway, so no worries about looking where it is actually stored. Thanks!
