### ISSUE TITLE
Suggestion: match by trace

### ISSUE THREAD

**Issue by jonathann403** [kevin-mizu/domloggerpp#13]

**Comment by kevin-mizu** [comment]
Thanks for the suggestion! Just before I start implementing it, what do you mean by "match by trace" exactly? Do you want to be able to log or not log / get a notification or not get a notification if a specific string/pattern is found within the stack trace itself, right?

I just wanted to be sure we are speaking about the same feature :D

**Comment by kevin-mizu** [comment]
Thanks again for pointing this out, it will be integrated in the next release :)
