### ISSUE TITLE
DomLogger++ isn't properly working on HTTP websites

### ISSUE THREAD

**Issue by FeelProud** [kevin-mizu/domloggerpp#14]
Hi Mizu,

DomLogger++ seems to not be properly working on HTTP websites.

For my test, I use your DomInvader configuration : [dom-invader.json](https://github.com/kevin-mizu/domloggerpp/blob/main/configs/dom-invader.json)
Then I activate it on a HTTP website, for example : http://www.columbia.edu/~fdc/

In the console logs, you can see this error : `Uncaught (in promise) TypeError: domlogger.func['crypto.subtle'] is undefined`.
Sometimes this error is repeating without stopping.

Hope you will be able to fix it easily 😄 
Thanks

**Comment by kevin-mizu** [comment]
Hey @FeelProud :p

Thanks for reporting this issue! It should be fixed now, and will be integrated in the next release 🎉
