### ISSUE TITLE
Support matching against "this" instance of functions.

### ISSUE THREAD

**Issue by aristosMiliaressis** [kevin-mizu/domloggerpp#16]
Hi Kevin,

i see that the "this" instance is logged in the console but is not available for the match functionality.
![image](https://github.com/user-attachments/assets/1ee7d984-b920-4b84-b680-593177371fa0)
![Screenshot 2024-07-18 152544](https://github.com/user-attachments/assets/c082e357-f56f-4b53-968e-206817587bd5)

**Comment by kevin-mizu** [comment]
Hey @aristosMiliaressis, thanks for this second issue!

This is a good idea. I'll also add this as an exec: match directive parameter. This would be super powerful in some specific execution flows.

**Comment by kevin-mizu** [comment]
After some local tests, I don't think it's a good idea to link the thisArg to the match function, as it would lead to a lot of side effects on many unexpected functions (even worse with the other sink types). As a compensation, I have added it to the exec: match directive, allowing easy custom regex flows based on a specific this.

What do you think about it?

**Comment by aristosMiliaressis** [comment]
sounds good, that way you won't break other peoples configs, the use case i wanted to accomplice was to track common fragment access patterns and i can do it now with this config.

```json
"String.prototype.substring|String.prototype.slice": {
  "match": [
	"exec:return thisArg.startsWith('#') || thisArg == '' ? /\\[1\\]/ : 'hdsjfjhsdfghsdjfghjsdfghjsd'"
  ]
}
```

**Comment by kevin-mizu** [comment]
I see, that's an interesting approach! Note that you can also directly access location.hash within the exec call. So, you could compare it with thisArg too. I've implemented something similar in the CSPT configuration here: https://github.com/kevin-mizu/domloggerpp/blob/main/configs/cspt.json. Maybe it could give you some ideas ;)
