### ISSUE TITLE
"Add current ETLD+1" doesn't work correctly

### ISSUE THREAD

**Issue by xnl-h4ck3r** [kevin-mizu/domloggerpp#17]
Hi Kevin
If you go to https://www.amazon.co.uk/ for example and click the "Add current ETLD+1"  button, it adds `co.uk` to the domains list.
I'm guessing you are just taking the last part of the domain and assuming only 1 dot i the TLD, but there are quite a few with 2 parts, and even some with 3 and 4.
Thanks
Xnl

**Comment by kevin-mizu** [comment]
Hey 👋

That's a good point, it should also impact IP links. Do you have any idea of a proper way to fix it?

**Comment by xnl-h4ck3r** [comment]
I'm not 100% what the best way would be to be honest. I don't know if there is a library that will do that for you.
You'd need to have a list of all possible TLDs and check in order, starting with the one's with 4 periods, then 3, then 2, then 1 until you match. I have used the lists attached to do something similar in bash before:
[allTLD_basic.txt](https://github.com/user-attachments/files/16289835/allTLD_basic.txt)
[allTLD.txt](https://github.com/user-attachments/files/16289836/allTLD.txt)
I'm sure someone must know a better way though!

**Comment by kevin-mizu** [comment]
What's complicated is that I need the code to be small. I don't want it to become super complex for a "less important" feature 🤔

The proposed fix seems like a good way to achieve this, but it still forces me to integrate several megabytes of text just for an "easy to add domain" button :(

I'll give me some time thinking of a way to fix this without to much code :D

**Comment by xnl-h4ck3r** [comment]
Yeah, that's the problem. Maybe just try to cater for the top 10 obvious one's like `.co.uk` etc. I'll have a think too if there's some easier low impact way

**Comment by kevin-mizu** [comment]
That could be a good way to fix this issue! I'll also integrate an IP regex to detect whenever the current domain is an IP.

**Comment by kevin-mizu** [comment]
After reflection, I realized that the JSON file isn't that big and only needs to be loaded within the popup menu. So, I decided to integrate it directly. Thanks again for pointing this out; it will be included in the next release :)
