### ISSUE TITLE
Suggestion: Option to customize the font

### ISSUE THREAD

**Issue by tharunet01** [kevin-mizu/domloggerpp#27]
It will be great to have the option to change the font through the extension settings menu.

**Comment by kevin-mizu** [comment]
Hey 👋

Thanks for this suggestion! I’ve had this in mind for a long time but never took the time to implement it until now.

I’ve just made the commit that adds this feature (https://github.com/kevin-mizu/domloggerpp/commit/e68d9cfc6d385928fd58ad64bff6d7506eea3682). Thanks again for pointing it out, it will be included in the next release! :)
