### ISSUE TITLE
Ability to match against 'this' instance of string functions.

### ISSUE THREAD

**Issue by aristosMiliaressis** [kevin-mizu/domloggerpp#3]
Hi Kevin, i want to hook the slice & substring functions but only match them if their argument is 1 and the string they are operating on starts with a fragment character, currently i see no way to match against the string instance they are operating on.

Thanks for the great work you do :)

**Comment by kevin-mizu** [comment]
Hi @aristosMiliaressis,

Thanks a lot for your interest!

You're right, I hadn't realized that it wasn't possible to retrieve information from the current caller object. This is something that has to be integrated for sure. I'll try to find a proper way to integrate this while keeping the original function arguments.

Thanks a lot 🙏

**Comment by kevin-mizu** [comment]
Thanks again for pointing this out, it will be integrated in the next release :)
