### ISSUE TITLE
Ability to save a configuration using CTRL+S shortcut

### ISSUE THREAD

**Issue by FeelProud** [kevin-mizu/domloggerpp#4]
A lot of people are used to saving their current work/task using CTRL+S keyboard shortcut in various software applications. When doing it to in order to save the current configuration changes in the application, it opens the browser's standard 'Save Page' function. It will be a good idea to override the typical browser response to CTRL+S (open the 'Save Page' dialog) by replacing it with saving the configuration changes.

**Comment by kevin-mizu** [comment]
Thanks for the suggestion, it will be integrated in the next release :)

**Comment by bsecure-mizu** [comment]
Whoops wrong issue, resetting the branch :x

**Comment by kevin-mizu** [comment]
whoops wrong issue, resetting the branch :x

**Comment by kevin-mizu** [comment]
Whoops wrong issue, resetting the branch :x
