### ISSUE TITLE
"_COMMENT" is an invalid root key

### ISSUE THREAD

**Issue by xnl-h4ck3r** [kevin-mizu/domloggerpp#6]
Hi Kevin
Thanks for the great extension!
The example on https://github.com/kevin-mizu/domloggerpp/blob/main/examples/cspp.json has a root key of "_comment".
If you try using that example, you can't save it because it gives an invalid JSON error because `"_COMMENT" is an invalid root key`.
Thanks

**Comment by kevin-mizu** [comment]
Hey 👋

Thanks for noticing it! It is fixed, and it will be integrated in the next release :)
